package com.candy.InterviewCoachAI.entity;

public enum SessionStatus {
    GENERATING, // questions are being generated by the Kafka consumer + AI
    READY,      // questions are generated and ready to answer
    FAILED      // AI generation failed - can be retried
}
